// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtzlturyendzmirvbofu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0emx0dXJ5ZW5kem1pcnZib2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzMyNDUsImV4cCI6MjA3NDEwOTI0NX0.k2TQs_Jezco4VGa1SrkOsmSptMeYHMMLh9sJIhuhHkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});